export const CHANGE_SEARCHFIELD = 'CHANGE_SEARCHFIELD';

export const REQUEST_PROFILES_PENDING = 'REQUEST_PROFILES_PENDING';
export const REQUEST_PROFILES_SUCCESS = 'REQUEST_PROFILES_SUCCESS';
export const REQUEST_PROFILES_FAILED = 'REQUEST_PROFILES_FAILED';
